name: "Sync Data"

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.DATAKHK_GITHUB_TOKEN}}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: make build
      - run: |
          git config user.name datakhk
          git config user.email opendatakhk@gmail.com
          git add .
          git commit -m "Data: sync $(date +'%Y-%m-%dT%H:%M:%S')" || true
          git push
